### ISSUE TITLE
Add Launcher Icon

### ISSUE THREAD

**Issue by BenAuerDev** [marqably/flites#46]
Now that flites is ready to be shown to the world, we should add also add a launcher icon. I think the easiest would be with [the launcher icons package](https://pub.dev/packages/flutter_launcher_icons). 

Note: In the [debian build](https://github.com/marqably/flites/blob/main/.github/workflows/debian_build.yaml) there is a command copying a placeholder icon.  This can be removed, if there are any conflicts. 

```yaml
- name: 🎨 Copy Icons
  run: |
    cp apps/flites/assets/icons/steps.svg debian/usr/share/icons/hicolor/scalable/apps/steps.svg
    chmod 644 debian/usr/share/icons/hicolor/scalable/apps/steps.svg
```
